model:
  input_dim: 28           # Number of input features in your processed CSV
  lr: 0.0008887654177594423              # Learning rate
  weight_decay: 0.003464121351653665    # L2 regularization
  batch_size: 32
  num_epochs: 100
  threshold: 0.4713132446200099
  seed: 42
  device: "cpu"           # or "cuda" if using GPU

data:
  path: "data/processed/telco_churn_processed.csv"