config_yaml = """
model:
  input_dim: 30  # Adjust after checking final feature count
  lr: 0.01
  weight_decay: 0.0001
  batch_size: 64
  num_epochs: 50
  threshold: 0.5
  seed: 42
  device: "cuda"  # or "cpu"
data:
  path: "data/processed/telco_churn_processed.csv"
"""