model:
  input_dim: 28           # Number of input features in your processed CSV
  lr: 0.0009013733307951182              # Learning rate
  weight_decay: 0.001538319274794674    # L2 regularization
  batch_size: 32
  max_epochs: 50
  patience: 5
  threshold: 0.5751320285992033
  seed: 42
  device: "cpu"           # or "cuda" if using GPU

data:
  path: "data/processed/telco_churn_processed.csv"